language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: trusty

env:
  - CAKEPHP_VERSION=4.3.*

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer require "cakephp/cakephp:${CAKEPHP_VERSION}" --no-update

install: composer update --with-dependencies --prefer-dist --no-interaction

script:
  - export CODECOVERAGE=1; vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
